### ISSUE TITLE
Fehler im Wiki

### ISSUE THREAD

**Issue by BackInBash** [TomSDEVSN/hetznercloud-java#11]
Hi, im Wiki auf der Seite:
https://github.com/TomSDEVSN/hetznercloud-java/wiki/Create-Server

Haben die Objekte falsche Namen:
```java
RequestServer requestServer = RequestServer.builder()
```
Es müsste mehr so aussehen:
```java
ServerRequest requestServer = ServerRequest.builder()
```

**Comment by TomSDEVSN** [comment]
ENGLISH BELOW
===

Hi,

das Wiki ist (leider) noch auf einem Stand von Version 1.1.5.
Da ich derzeit Prüfungen habe, habe ich nicht allzu viel Zeit dazu es zu aktualisieren.
Ich nehme es mir aber definitiv vor es zu aktualisieren nach den Prüfungen (wenn ich nicht arbeiten gehe).

Viele Grüße
Tom

ENGLISH
===

Hi,
currently, the Wiki is still (sadly) on a version for 1.1.5.
Since I currently have exams, I don't have much time to update it.
I will refresh it after the exams if I have not to work.

Best Regards,
Tom
