### ISSUE TITLE
Android compatibility 

### ISSUE THREAD

**Issue by LouisPouliot** [TomSDEVSN/hetznercloud-java#16]
I am encountering issues while trying to use this library from an android app .
Calling HetznerCloudApi.getSSHKeys results in a RuntimeException caused by an EOFException.
Is this API not android compatible?

**Comment by TomSDEVSN** [comment]
Which version of the API do you use?
For a deeper debug, upload the source code and the Exception you get to GitHub Gist, please.

**Comment by LouisPouliot** [comment]
I am using version 2.8.0
[The gist with the exception and the method call](https://gist.github.com/LouisPouliot/603adaddb314735f41edd2adc8d50851)

**Comment by TomSDEVSN** [comment]
Okay, that's strange. I'll some debugging and see if there is a bug in API Backend or a bug in Spring.

**Comment by TomSDEVSN** [comment]
Okay, I think I found the issue.
I will try to compile a version which maybe works with Android.

**Comment by TomSDEVSN** [comment]
I've taken a deeper look now and it seems to be an issue with okhttp and Spring which can't be easily fixed with older/newer dependencies or special android dependencies. For this time, I've to say (sadly) that this client is not android compatible.

If I'll be able to find something that could solve the problem I would post it in this issue.

**Comment by LouisPouliot** [comment]
Thank you for looking into it
